export type Difficulty = "simple" | "medium" | "advanced" | "professional";

export const DIFFICULTIES: { value: Difficulty; label: string; shortLabel: string }[] = [
  { value: "simple", label: "簡單", shortLabel: "Simple" },
  { value: "medium", label: "中等", shortLabel: "Medium" },
  { value: "advanced", label: "高級", shortLabel: "Advanced" },
  { value: "professional", label: "專業", shortLabel: "Professional" },
];

export type DailyLesson = {
  id: string;
  day: number;
  difficulty: Difficulty;
  title: string;
  level: string;
  duration: string;
  script: string;
  questions: [string, string];
  keyPhrases: string[];
  naturalAnswer: string;
};

type LessonInput = Omit<DailyLesson, "id" | "level"> & { slug: string };

function makeLesson(input: LessonInput): DailyLesson {
  const difficultyLabel = DIFFICULTIES.find((item) => item.value === input.difficulty)?.label ?? "中等";
  return { ...input, id: `${input.slug}-day-${input.day}`, level: `${difficultyLabel} · American English` };
}

export const LESSONS: DailyLesson[] = [
  makeLesson({ day: 1, difficulty: "simple", slug: "morning-routine", title: "A calm morning", duration: "0:34", script: "I usually wake up at seven and open the curtains right away. Then I drink a glass of water, make toast, and check my schedule before I leave home.", questions: ["What does the speaker drink?", "What does the speaker check?"], keyPhrases: ["seven", "curtains", "water", "schedule"], naturalAnswer: "The speaker drinks water and checks the schedule before leaving home." }),
  makeLesson({ day: 2, difficulty: "simple", slug: "coffee-shop-order", title: "A coffee shop order", duration: "0:38", script: "I stopped by the coffee shop before class and ordered a small iced latte. The barista said they were out of oat milk, so I chose regular milk instead.", questions: ["What did the speaker order?", "Why did the speaker choose regular milk?"], keyPhrases: ["iced latte", "oat milk", "regular milk", "barista"], naturalAnswer: "The speaker ordered an iced latte with regular milk because oat milk was unavailable." }),
  makeLesson({ day: 3, difficulty: "simple", slug: "weekend-hike", title: "Planning a weekend hike", duration: "0:45", script: "A few friends and I are planning to hike this Saturday. We wanted to start at eight, but it might rain in the morning. We’ll meet at ten instead and bring rain jackets.", questions: ["When will they meet?", "What will they bring?"], keyPhrases: ["Saturday", "ten", "rain", "jackets"], naturalAnswer: "They will meet at ten and bring rain jackets because it might rain." }),
  makeLesson({ day: 4, difficulty: "simple", slug: "grocery-list", title: "The grocery list", duration: "0:40", script: "Before heading home, I checked the grocery list on my phone. We needed eggs, rice, and vegetables, but we still had plenty of bread.", questions: ["Which food did they already have?", "Where was the list?"], keyPhrases: ["eggs", "rice", "vegetables", "bread"], naturalAnswer: "They already had bread, and the grocery list was on the speaker’s phone." }),
  makeLesson({ day: 5, difficulty: "simple", slug: "lost-package", title: "A missing package", duration: "0:39", script: "My delivery notice said the package was at my front door, but I couldn’t find it. My neighbor had accepted it while I was at work, so I picked it up after dinner.", questions: ["Who accepted the package?", "When did the speaker pick it up?"], keyPhrases: ["delivery", "front door", "neighbor", "after dinner"], naturalAnswer: "The neighbor accepted the delivery, and the speaker picked it up after dinner." }),
  makeLesson({ day: 6, difficulty: "simple", slug: "movie-night", title: "Choosing a movie", duration: "0:37", script: "My sister and I wanted to watch a movie, but we couldn’t agree. She wanted a comedy, while I preferred a mystery. We found a mystery with funny characters.", questions: ["What genre did the sister want?", "What did they finally choose?"], keyPhrases: ["sister", "comedy", "mystery", "funny"], naturalAnswer: "The sister wanted a comedy, but they chose a funny mystery." }),
  makeLesson({ day: 7, difficulty: "simple", slug: "bus-stop", title: "Waiting for the bus", duration: "0:35", script: "I got to the bus stop early, but the bus was running ten minutes late. I listened to music while I waited, and the driver apologized when the bus arrived.", questions: ["How late was the bus?", "What did the speaker do while waiting?"], keyPhrases: ["bus stop", "early", "ten minutes", "music"], naturalAnswer: "The bus was ten minutes late, so the speaker listened to music." }),
  makeLesson({ day: 8, difficulty: "simple", slug: "new-neighbor", title: "Meeting a new neighbor", duration: "0:36", script: "A new neighbor moved into the apartment next door. I introduced myself and gave her a list of nearby restaurants. She invited me over for coffee next weekend.", questions: ["What did the speaker give the neighbor?", "What did the neighbor suggest?"], keyPhrases: ["new neighbor", "introduced", "restaurants", "coffee"], naturalAnswer: "The speaker gave the neighbor restaurant recommendations, and she invited them for coffee." }),

  makeLesson({ day: 9, difficulty: "medium", slug: "airport-check-in", title: "Checking in at the airport", duration: "0:48", script: "At the airport, I checked in online before joining the baggage line. The agent asked whether I had packed my own suitcase and printed a new boarding pass because my phone was almost out of power.", questions: ["Why did the agent print a boarding pass?", "What did the agent ask about the suitcase?"], keyPhrases: ["airport", "baggage line", "packed", "boarding pass"], naturalAnswer: "The agent printed the pass because the phone battery was low and asked whether the traveler packed the suitcase." }),
  makeLesson({ day: 10, difficulty: "medium", slug: "team-lunch", title: "A team lunch", duration: "0:44", script: "Our team planned lunch at a new Thai restaurant downtown. One coworker had a meeting, so we saved her a seat and ordered an extra portion of noodles. She arrived just before dessert.", questions: ["Why was one coworker late?", "What did the team save for her?"], keyPhrases: ["Thai restaurant", "meeting", "seat", "noodles"], naturalAnswer: "The coworker had a meeting, so the team saved a seat and ordered noodles for her." }),
  makeLesson({ day: 11, difficulty: "medium", slug: "doctor-appointment", title: "Changing an appointment", duration: "0:43", script: "I called the clinic to move my appointment to next week. The receptionist offered Tuesday morning or Wednesday afternoon. I chose Wednesday because I have a meeting on Tuesday.", questions: ["Why did the speaker change the appointment?", "Which new time did they choose?"], keyPhrases: ["clinic", "next week", "Wednesday", "meeting"], naturalAnswer: "The speaker changed the appointment because of a Tuesday meeting and chose Wednesday afternoon." }),
  makeLesson({ day: 12, difficulty: "medium", slug: "repair-shop", title: "At the repair shop", duration: "0:49", script: "My laptop started making a strange noise, so I took it to a repair shop. The technician found dust near the fan and said it would be ready by Friday afternoon.", questions: ["What problem did the laptop have?", "When will it be ready?"], keyPhrases: ["laptop", "strange noise", "dust", "Friday afternoon"], naturalAnswer: "The laptop was making a strange noise because of dust near the fan, and it will be ready Friday afternoon." }),
  makeLesson({ day: 13, difficulty: "medium", slug: "library-card", title: "Getting a library card", duration: "0:46", script: "I visited the library to get a card for my new apartment. The librarian asked for my ID and proof of address. I borrowed two novels and learned that language classes meet there on Thursdays.", questions: ["What documents did the librarian request?", "What classes meet at the library?"], keyPhrases: ["library card", "ID", "proof of address", "language classes"], naturalAnswer: "The librarian requested ID and proof of address, and the library offers language classes on Thursdays." }),
  makeLesson({ day: 14, difficulty: "medium", slug: "weather-change", title: "A change in the weather", duration: "0:42", script: "The forecast called for sunshine, but dark clouds appeared during our picnic. We packed the food quickly and moved under a covered patio before the rain started.", questions: ["What did the forecast predict?", "Where did they move?"], keyPhrases: ["forecast", "sunshine", "dark clouds", "covered patio"], naturalAnswer: "The forecast predicted sunshine, but they moved under a covered patio before it rained." }),
  makeLesson({ day: 15, difficulty: "medium", slug: "online-order", title: "Fixing an online order", duration: "0:47", script: "The headphones I ordered arrived in the wrong color. Customer service apologized and offered a free return label. I decided to exchange them instead of asking for a refund.", questions: ["What was wrong with the order?", "What did the customer decide to do?"], keyPhrases: ["headphones", "wrong color", "return label", "exchange"], naturalAnswer: "The headphones were the wrong color, and the customer chose an exchange instead of a refund." }),
  makeLesson({ day: 16, difficulty: "medium", slug: "houseplants", title: "Taking care of houseplants", duration: "0:41", script: "My friend asked me to water her plants while she was away. She left them near the window and told me to water the fern every other day, but only once a week for the cactus.", questions: ["How often should the fern be watered?", "Where are the plants?"], keyPhrases: ["water", "away", "window", "every other day"], naturalAnswer: "The fern needs water every other day, and the plants are near the window." }),

  makeLesson({ day: 17, difficulty: "advanced", slug: "project-deadline", title: "A shifting project deadline", duration: "0:55", script: "The product launch was originally scheduled for the end of the month, but a delay in testing pushed the timeline back by two weeks. The team is prioritizing the highest-impact fixes so the revised date remains realistic.", questions: ["Why was the launch delayed?", "What is the team prioritizing?"], keyPhrases: ["product launch", "testing", "two weeks", "highest-impact fixes"], naturalAnswer: "Testing caused a two-week delay, so the team is prioritizing the most important fixes." }),
  makeLesson({ day: 18, difficulty: "advanced", slug: "rent-negotiation", title: "Discussing a lease renewal", duration: "0:52", script: "When my lease came up for renewal, the landlord proposed a higher monthly rate. I explained that comparable units in the neighborhood were cheaper and offered to sign a longer lease in exchange for a smaller increase.", questions: ["What did the landlord propose?", "What did the tenant offer?"], keyPhrases: ["lease renewal", "higher rate", "comparable units", "longer lease"], naturalAnswer: "The landlord proposed a rent increase, and the tenant offered a longer lease for a smaller increase." }),
  makeLesson({ day: 19, difficulty: "advanced", slug: "research-summary", title: "Summarizing research", duration: "0:58", script: "The research suggests that short, consistent practice produces better long-term retention than occasional intensive sessions. However, the participants who received immediate feedback improved their accuracy most quickly.", questions: ["What practice pattern supports retention?", "Who improved accuracy fastest?"], keyPhrases: ["consistent practice", "long-term retention", "immediate feedback", "accuracy"], naturalAnswer: "Short consistent practice supports retention, while immediate feedback helped participants improve accuracy fastest." }),
  makeLesson({ day: 20, difficulty: "advanced", slug: "career-transition", title: "Planning a career transition", duration: "0:54", script: "After several years in operations, Maya is considering a transition into user research. She is taking an evening course, interviewing practitioners, and building a portfolio before applying for entry-level roles.", questions: ["What field is Maya considering?", "What is she doing before applying?"], keyPhrases: ["operations", "user research", "evening course", "portfolio"], naturalAnswer: "Maya is moving toward user research and is taking a course, interviewing practitioners, and building a portfolio." }),
  makeLesson({ day: 21, difficulty: "advanced", slug: "community-budget", title: "Reviewing a community budget", duration: "1:01", script: "The committee approved the playground renovation, but only after reallocating funds from the unused events budget. The chair emphasized that the change would not affect emergency reserves or next year’s maintenance plan.", questions: ["Where did the committee find funding?", "What will remain unaffected?"], keyPhrases: ["playground renovation", "reallocating funds", "events budget", "emergency reserves"], naturalAnswer: "The committee moved money from the unused events budget without affecting emergency reserves or maintenance." }),
  makeLesson({ day: 22, difficulty: "advanced", slug: "ethical-design", title: "An ethical design review", duration: "0:57", script: "During the design review, the team questioned whether a notification pattern encouraged unnecessary engagement. They decided to test a quieter default and measure satisfaction rather than optimizing solely for daily opens.", questions: ["What pattern did the team question?", "What will they measure?"], keyPhrases: ["design review", "unnecessary engagement", "quieter default", "satisfaction"], naturalAnswer: "They questioned a notification pattern and will test a quieter default while measuring user satisfaction." }),
  makeLesson({ day: 23, difficulty: "advanced", slug: "supply-chain", title: "A supply chain update", duration: "0:59", script: "The supplier confirmed that the component shortage is easing, although shipping capacity remains constrained in several regions. The operations team is diversifying routes to reduce the risk of another interruption.", questions: ["What problem is improving?", "What is the operations team changing?"], keyPhrases: ["component shortage", "shipping capacity", "diversifying routes", "interruption"], naturalAnswer: "The component shortage is easing, and the team is diversifying shipping routes to reduce interruptions." }),

  makeLesson({ day: 24, difficulty: "professional", slug: "quarterly-forecast", title: "A quarterly forecast", duration: "1:08", script: "The revised quarterly forecast reflects slower demand in the enterprise segment, partially offset by stronger retention among smaller accounts. Finance recommends preserving a conservative hiring plan until the next two reporting cycles provide clearer evidence.", questions: ["What reduced the forecast?", "What does Finance recommend?"], keyPhrases: ["quarterly forecast", "slower demand", "retention", "conservative hiring"], naturalAnswer: "Slower enterprise demand reduced the forecast, so Finance recommends conservative hiring until more data arrives." }),
  makeLesson({ day: 25, difficulty: "professional", slug: "stakeholder-alignment", title: "Aligning stakeholders", duration: "1:04", script: "Before committing to the integration timeline, the product lead asked stakeholders to distinguish non-negotiable requirements from desirable enhancements. That exercise exposed a dependency that would otherwise have surfaced during implementation.", questions: ["What distinction did the product lead request?", "What did the exercise reveal?"], keyPhrases: ["integration timeline", "non-negotiable", "desirable enhancements", "dependency"], naturalAnswer: "Stakeholders separated essential requirements from enhancements, revealing an implementation dependency." }),
  makeLesson({ day: 26, difficulty: "professional", slug: "privacy-review", title: "A privacy review", duration: "1:10", script: "The privacy review found that the proposed analytics event contained more user context than the team needed for the stated purpose. The engineers will reduce the payload, document retention limits, and add an opt-out path before launch.", questions: ["What issue did the review find?", "What changes will engineers make?"], keyPhrases: ["privacy review", "analytics event", "payload", "opt-out"], naturalAnswer: "The analytics event collected unnecessary context, so the team will reduce the payload, limit retention, and add opt-out controls." }),
  makeLesson({ day: 27, difficulty: "professional", slug: "incident-retrospective", title: "An incident retrospective", duration: "1:12", script: "The retrospective concluded that the outage was not caused by a single error but by several safeguards failing in sequence. The action plan therefore focuses on earlier detection, clearer ownership, and a tested rollback procedure.", questions: ["How did the outage happen?", "What does the action plan focus on?"], keyPhrases: ["retrospective", "safeguards", "earlier detection", "rollback"], naturalAnswer: "Several safeguards failed in sequence, so the plan emphasizes detection, ownership, and rollback." }),
  makeLesson({ day: 28, difficulty: "professional", slug: "market-entry", title: "Evaluating market entry", duration: "1:06", script: "The market-entry proposal has attractive growth potential, but regulatory requirements vary substantially across the target regions. The strategy group recommends a limited pilot to validate demand and compliance assumptions before scaling.", questions: ["What makes the proposal risky?", "What does the strategy group recommend?"], keyPhrases: ["market entry", "regulatory requirements", "limited pilot", "scaling"], naturalAnswer: "Regional regulations create risk, so the team recommends a limited pilot before scaling." }),
  makeLesson({ day: 29, difficulty: "professional", slug: "board-update", title: "Preparing a board update", duration: "1:03", script: "For the board update, the CEO wants the narrative to connect operating metrics with the company’s strategic priorities. Rather than presenting every dashboard, the team will highlight the few indicators that explain the quarter’s key decisions.", questions: ["What should the narrative connect?", "Which metrics will the team highlight?"], keyPhrases: ["board update", "operating metrics", "strategic priorities", "key decisions"], naturalAnswer: "The narrative should connect operating metrics with strategy and focus on indicators behind key decisions." }),
  makeLesson({ day: 30, difficulty: "professional", slug: "long-term-planning", title: "Long-term planning", duration: "1:09", script: "The leadership team agreed that the next planning cycle should begin with a small set of measurable outcomes rather than a list of initiatives. Each proposed investment will be evaluated against those outcomes, with assumptions revisited quarterly.", questions: ["What should planning begin with?", "How will investments be evaluated?"], keyPhrases: ["planning cycle", "measurable outcomes", "investments", "assumptions"], naturalAnswer: "Planning will begin with measurable outcomes, and investments will be evaluated against them each quarter." }),
];

const PROGRAM_START = new Date(2026, 8, 25);

export function getDailyLesson(date = new Date(), difficulty: Difficulty = "simple") {
  const calendarDate = new Date(date.getFullYear(), date.getMonth(), date.getDate());
  const dayDistance = Math.floor((calendarDate.getTime() - PROGRAM_START.getTime()) / 86_400_000);
  const normalizedDay = ((dayDistance % 30) + 30) % 30;
  const pool = LESSONS.filter((lesson) => lesson.difficulty === difficulty);
  return pool[normalizedDay % pool.length] ?? LESSONS[normalizedDay];
}
